### ISSUE TITLE
Jenkins cannot build due to invalid yml

### ISSUE THREAD

**Issue by aguerre** [jreziga/JrkLevenshteinBundle#1]
I've this issue when trying to build my app in Jenkins, especially when tests are launched:
`Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The file "/var/lib/jenkins/workspace/FooProject/vendor/jrk/levenshtein-bundle/Jrk/LevenshteinBundle/DependencyInjection/../Resources/config/services.yml" does not contain valid YAML.`

But the services.yml seems correct, and works on my local project...

PS: dédicace Jessym du 6-9 !

**Comment by aguerre** [comment]
`Caused by
     [exec] Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 6 (near "arguments: [@doctrine.orm.entity_manager]").`

Need to be adapted to latest Symfony versions

**Comment by jr-k** [comment]
It's updated. Now I recommend you to use "1.0" tag in your composer.json.

Thanks !
